### ISSUE TITLE
ctx.Arg(0) is always nil

### ISSUE THREAD

**Issue by SharpBit** [sapphire-cord/sapphire#3]
It's supposed to return the first arg but it actually returns nil every time
Example:
`//kick @Silver#0543 offline forever`

ctx.Args: `[<nil> 0xc0001583e0 0xc000158400 0xc000158440]`
ctx.Arg(2): `&{offline true}`

**Comment by ravener** [comment]
What's your usage string, also be sure to run spgen everytime you modify any of those comments.

**Comment by SharpBit** [comment]
wrong usage string whops
