### ISSUE TITLE
Add different types of monitors

### ISSUE THREAD

**Issue by SharpBit** [sapphire-cord/sapphire#4]
1. When a command func is called
2. When panic() is called inside a function

idk if these are possible but i just wanted to write my ideas so i dont forget them later

**Comment by ravener** [comment]
What do you mean with those points, command handler is a monitor and it has a panic handler that gives the error to your error handler (`bot.SetErrorHandler`) additionally the error can be cast to *CommandError to get more context of the error.

**Comment by ravener** [comment]
Monitors are also not events it's simply a way to listen to messages, closing this for now.
